---
title: "Learining R3"
author: "Kristina Matthiesen Hansen"
format: html
---


```{r}
library(readr)
library(tidyverse)
library(here)
library(snakecase)
```

# Session-section

Importing new data

Snakecase er den bedste måde at gøre det på - det ser pænere ud

```{r importdata}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
``` 

## Exercise: Reading other files.
```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```


New participant 
```{r newP}
here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case
  )
```
```{r}
here("data-raw/nurses-stress/stress/6B/6B_1587569373/EDA.csv.gz") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

```{r function}
#' Add two numbers together
#'
#' @param num1 A number here.
#' @param num2 A number here.
#'
#' @returns Returns the sum of two numbers.
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}
```

```{r}
#' Read in one nurses-stress data file
#'
#' @param file_path
#'
#' @returns A path to a data file
#' @export outputs a data frame/tibble
#'
#' @examples
read <- function(file_path) {
  data <- file_path |>
    read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = 100
    )
  return(data)
}
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886626/HR.csv.gz") |>
  read()
```

```{r}
here("data-raw/nurses-stress/stress/5C/5C_1586886712/HR.csv.gz") |>
  read()
```
